// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalaryProject.DAL.EFCore.Contexts;

#nullable disable

namespace SalaryProject.DAL.EFCore.Migrations
{
    [DbContext(typeof(SalaryDbContext))]
    [Migration("20230724110102_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SalaryProject.Domain.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AttractionRight")
                        .HasColumnType("float")
                        .HasColumnName("attraction_right");

                    b.Property<double>("BasicSalary")
                        .HasColumnType("float")
                        .HasColumnName("basic_salary");

                    b.Property<double>("CommutingRight")
                        .HasColumnType("float")
                        .HasColumnName("commuting_right");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2")
                        .HasColumnName("birth_date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("last_name");

                    b.Property<double>("OvertimeAmount")
                        .HasColumnType("float")
                        .HasColumnName("overtime_amount");

                    b.Property<DateTime>("SalaryDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("salary_date");

                    b.HasKey("Id");

                    b.HasIndex("FirstName", "LastName", "SalaryDate")
                        .IsUnique();

                    b.ToTable("tbl_employees", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
